### ISSUE TITLE
Change issue count on LPA dashboard dataset card

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#439]
## Context:

- We've recently changed how we handle instances where a dataset is missing an entire column, so that we're treating it as a single issue for the user to fix, rather than counting each record/entity as a separate issue.
- We've changed the content on the issues tasklist page to reflect this:

----
![Image](https://github.com/user-attachments/assets/b13d9e6a-54e2-4450-bccb-d1b7e7da217b)

----
- However, when you view the dataset card on the LPA dashboard page, it's showing the total issue count on a 'per record/entity' basis:

----
![Image](https://github.com/user-attachments/assets/b8510de2-b30f-49d5-86cf-a016970a4636)
----

- I'm presuming that we should just treat this as a single issue in the count - @alextea can you confirm that's the best approach?

**Comment by alextea** [comment]
@CharliePatterson yes, as a single issue

**Comment by gmatchett** [comment]
Samriti Sadhu  [10:28 AM]
FYI - I am talking to Roland now as he messaged me with the same issue.
"It looks like the two queries are addressing different issues:
For the 'article-4-direction' pipeline, there are 12 entities, and each entity has issues with two fields: document-url and documentation-url. Since all rows have missing values for both fields, the total count of issues is 24.
For the 'article-4-direction-area', there are 233 entities, but the issue reported in your query is a warning for invalid geometry in just one row. You can verify this here: [Datasette Query](https://datasette.planning.data.gov.uk/article-4-direction-area/issue?_sort=rowid&issue_type__contains=geometry&resource__exact=565974e9b7f4989fc45c9f702b9b66a958d141a3d98e038f2560ed3aa5535384).
Additionally, the error count isn't displayed in your query, possibly due to an issue with the query itself. You can cross-check the results with these queries:
[Provision Summary](https://datasette.planning.data.gov.uk/performance/provision_summary?_sort=rowid&dataset__contains=article-4-direction-area&organisation__contains=LBH)
[Issue Summary](https://datasette.planning.data.gov.uk/performance/issue_summary?_sort=rowid&resource__exact=565974e9b7f4989fc45c9f702b9b66a958d141a3d98e038f2560ed3aa5535384)
Let me know if you need any help with this or further clarificatin

**Comment by rosado** [comment]
Moving back to dev due to performancedb changes.
