### ISSUE TITLE
Evaluate impact of upcoming performance db changes

### ISSUE THREAD

**Issue by GeorgeGoodall-GovUk** [digital-land/submit#497]
# Problem statement

Infa is currently working on some more changes on the performance db, we need to make sure these changes don't break our service

https://trello.com/c/NJSZQBUZ/3512-perf-db-general-changes?filter=label:Infrastructure
https://trello.com/c/VZDUrdFJ/3511-perf-db-changes-to-specific-tables?filter=label:Infrastructure

# Longer term considerations

The performance database is still in its infancy, and needs feedback from us to grow further. however utilizing the perfDb further could create more upstream risk 

ideally we need infa to produce an API we query, then we need to work with them to obtain exactly the data we want

**Comment by ssadhu-sl** [comment]
The changed included in this sprint:
**Provision_summary table**
name-> organisation_name
count_internal_issue->count_issue_error_internal
count_internal_issue->count_issue_error_external
count_internal_warning->count_issue_warning_internal
count_external_warning->count_issue_warning_external
count_internal_notice->count_issue_notice_internal
count_external_notice->count_issue_notice_external

**Issue_summary table**(renamed)→ endpoint_dataset_issue_type_summary
count_issues-> type changed to Integer
Column_field_summary(renamed) → endpoint_dataset_resource_summary
matching_field->mapping_field
non_matching_field-> non_mapping_field
Field match summary fields are now semi-colon separated instead of comma

These changes will be deployed soon(today/tomorrow):
Rename status -> latest status
Rename exception -> latest_exception
Removed extraneous columns for issue_type_summary and resource_summary tables (status, exception, endpoint entry date, endpoint end date)
Removed entries with blank resources for the above tables
Removed timestamps from dates
Added 'endpoint_dataset_summary' table
